server:
  context-path: /dy

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect

mybatis:
  type-aliases-package: com.fanxl.dynamic.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #对象驼峰命名和数据库下横线的转换